package org.intense;

public enum TokenType {
    LPAREN, RPAREN,
    LLIST, RLIST,
    LBRACE, RBRACE,
    SYMBOL, NUMBER,
    STRING, BOOLEAN,
    QUOTE, QUASIQUOTE,
    UNQUOTE, UNQUOTE_SPLICING,
    REQUIERE,
    COLON, EOF,
    IF,DEF,THIS,
    Closure,
    BIG_INT,
    INT,
    FLOAT,
    LONG,
    DOUBLE,
    OBJECT,
    ARRAY_INT,
    ARRAY_DOUBLE,
    ARRAY_OBJECT,
    UNDEFINED,
    SET, PACKAGE, WHILE, FOR, MAP_KEY, GET, VAR, VAL, FUN, SELF, NULL, BYTE, SHORT, UBYTE, ULONG, NULLABLE, DOT, STRING_KEYWORD, INT_KEYWORD, DOUBLE_KEYWORD, BOOLEAN_KEYWORD, FLOAT_KEYWORD, BYTE_KEYWORD, SHORT_KEYWORD, LONG_KEYWORD, UBYTE_KEYWORD, ULONG_KEYWORD, INVALID
}
